run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - gocyclo
    - goconst
    - unconvert
    - unparam
    - misspell
    - nolintlint

issues:
  exclude-use-default: false
